version: "3.8"

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - PYTHONUNBUFFERED=1
      - DATABASE_URL=sqlite:///app/fitness_tracker.db
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    depends_on:
      - db

  llm_chatbot_microservice:
    build:
      context: ./backend/LLM_CHATBOT
    ports:
      - "8001:8001"
    environment:
      - MISTRAL_API_KEY=${MISTRAL_API_KEY}
    volumes:
      - ./backend/LLM_CHATBOT:/app

  db:
    image: mariadb:10.5
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fitness
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    stdin_open: true
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    restart: on-failure

volumes:
  db_data: